---
- name: create our vms
  vcd_vapp_vm:
    target_vm_name: "{{ item.name }}"
    target_vapp: "{{ item.vapp }}"
    ip_allocation_mode: " {{ allocation_mode }}"
    power_on: false
    state: present
  with_items: "{{ vms }}"
